/**
 * Permission for staff DUNNIO ERP
 * @Public
 */
module.exports = {
    /** for order */
    ORDER_LIST: 'ORDER_LIST',
    ORDER_DETAIL: 'ORDER_LIST',
    ORDER_CREATE: 'ORDER_CREATE',
    ORDER_UPDATE: 'ORDER_UPDATE',
    ORDER_DELETE: 'ORDER_DELETE',

    /** for item */
    ITEM_LIST: 'ITEM_LIST',
    ITEM_DETAIL: 'ITEM_LIST',
    ITEM_CREATE: 'ITEM_CREATE',
    ITEM_UPDATE: 'ITEM_UPDATE',
    ITEM_DELETE: 'ITEM_DELETE',

    /** for item production */
    ITEM_ASSIGN: 'ITEM_ASSIGN',

    /** for production */
    DELIVERY_LIST: 'DELIVERY_LIST',
    DELIVERY_CREATE: 'DELIVERY_CREATE',
    DELIVERY_DETAIL: 'DELIVERY_LIST',
    DELIVERY_UPDATE: 'DELIVERY_UPDATE',

    /** for delivery */
    PRODUCTION_LIST: 'PRODUCTION_LIST',
    PRODUCTION_ASSIGN: 'PRODUCTION_ASSIGN',
    PRODUCTION_UPDATE: 'PRODUCTION_UPDATE',
    PRODUCTION_DETAIL: 'PRODUCTION_LIST',

    /** for promotion */
    PRICE_BOOK_LIST: 'PRICE_BOOK_LIST',
    PRICE_BOOK_CREATE: 'PRICE_BOOK_CREATE',
    PRICE_BOOK_UPDATE: 'PRICE_BOOK_UPDATE',
    PRICE_BOOK_DELETE: 'PRICE_BOOK_DELETE'
};
